# Generated by Django 3.2.3 on 2021-06-26 14:58

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('main_image', models.ImageField(default='none', upload_to='images')),
                ('Area', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('price', models.IntegerField()),
                ('slug', models.CharField(max_length=100)),
                ('sell_or_rent', models.IntegerField(choices=[('Sell', 'Sell'), ('Rent', 'Rent')])),
                ('timestamp', models.DateTimeField(verbose_name=True)),
                ('location', models.CharField(max_length=150)),
                ('property_type', models.IntegerField(choices=[('Office', 'Office'), ('Shop', 'Shop'), ('Storage', 'Storage'), ('Land', 'Land'), ('Hospitality', 'Hospitality'), ('Other', 'Other')])),
                ('photos', models.FileField(blank=True, upload_to='')),
                ('comstruction_status', models.IntegerField(choices=[('Ready to Move', 'Ready to Move'), ('Under Construction', 'Under Construction')])),
                ('amenities', multiselectfield.db.fields.MultiSelectField(choices=[('key1', 'Near to School'), ('key2', 'Near to Hospital'), ('key3', 'Close to Airport'), ('key4', 'Close to Market')], max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=250)),
                ('subject', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='page_nav/images/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.commercial')),
            ],
        ),
    ]
