# Generated by Django 3.2.3 on 2021-06-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='comstruction_status',
            field=models.CharField(choices=[('Ready to Move', 'Ready to Move'), ('Under Construction', 'Under Construction')], max_length=20),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='property_type',
            field=models.CharField(choices=[('Office', 'Office'), ('Shop', 'Shop'), ('Storage', 'Storage'), ('Land', 'Land'), ('Hospitality', 'Hospitality'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='sell_or_rent',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Rent', 'Rent')], max_length=20),
        ),
    ]
