# Generated by Django 3.2.4 on 2021-06-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('titel', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('price', models.IntegerField()),
                ('timestamp', models.DateTimeField(verbose_name=True)),
            ],
        ),
    ]
