# Generated by Django 3.2.4 on 2021-07-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercial',
            name='slug',
        ),
        migrations.AlterField(
            model_name='commercial',
            name='floorplan',
            field=models.ImageField(default='none', upload_to='folder_str/'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='main_image',
            field=models.ImageField(default='none', upload_to='folder_str/'),
        ),
    ]
