# Generated by Django 3.2.4 on 2021-06-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_commercial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercial',
            old_name='titel',
            new_name='title',
        ),
    ]
