# Generated by Django 3.2.3 on 2021-06-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210626_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercial',
            old_name='photos',
            new_name='floorplan',
        ),
    ]
