# Generated by Django 3.2.4 on 2021-06-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_titel_commercial_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='sell_or_rent',
            field=models.CharField(choices=[('1', 'Sell'), ('2', 'Rent')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
