# Generated by Django 3.2.4 on 2021-06-30 09:29

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_comstruction_status_commercial_construction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residential',
            fields=[
                ('main_image', models.ImageField(default='none', upload_to='images')),
                ('Area', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('price', models.IntegerField()),
                ('slug', models.CharField(max_length=100)),
                ('sell_or_rent', models.CharField(choices=[('Sell', 'Sell'), ('Rent', 'Rent')], max_length=20)),
                ('timestamp', models.DateTimeField(verbose_name=True)),
                ('location', models.CharField(max_length=150)),
                ('property_type', models.CharField(choices=[('RK', 'RK'), ('1 BHK', '1 BHK'), ('1.5 BHK', '1.5 BHK'), ('2 BHK', '2 BHK'), ('2.5 BHK', '2.5 BHK'), ('3 BHK', '3 BHK'), ('3.5 BHK', '3.5 BHK'), ('4 BHK', '4 BHK'), ('5 BHK', '5 BHK')], max_length=20)),
                ('floorplan', models.FileField(blank=True, upload_to='')),
                ('construction_status', models.CharField(choices=[('Ready to Move', 'Ready to Move'), ('Under Construction', 'Under Construction')], max_length=20)),
                ('amenities', multiselectfield.db.fields.MultiSelectField(choices=[('key1', 'Near to School'), ('key2', 'Near to Hospital'), ('key3', 'Close to Airport'), ('key4', 'Close to Market'), ('key5', 'Swimming Pool'), ('key6', 'Gym/Fitness Centers'), ('key7', 'Community Clubhouse'), ('key8', 'Community Garden'), ('key9', 'Guest Parking'), ('key10', 'Security Guards'), ('key11', 'CCTV Camera Security'), ('key12', 'Power Backup'), ('key13', '24/7 Water supply'), ('key14', 'Movie Theater'), ('key15', 'Power backup'), ('key16', 'Waste disposal'), ('key17', 'Fire Fighting Systems'), ('key18', 'Senior Citizen Sitout'), ('key19', 'Vastu Compliant'), ('key20', 'Entrance Lobby')], max_length=110)),
            ],
        ),
        migrations.CreateModel(
            name='PostRESIImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='page_nav/images/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.residential')),
            ],
        ),
    ]
