# Generated by Django 3.2.4 on 2021-06-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_commercial_sell_or_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='sell_or_rent',
            field=models.IntegerField(choices=[(1, 'Sell'), (2, 'Rent')], max_length=10),
        ),
    ]
