# Generated by Django 3.2.4 on 2021-06-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_postresiimage_residential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postresiimage',
            name='images',
            field=models.FileField(upload_to='resipage_nav/images/'),
        ),
    ]
