# Generated by Django 3.2.4 on 2021-06-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_commercial_sell_or_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='slug',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commercial',
            name='sell_or_rent',
            field=models.IntegerField(choices=[(1, 'Sell'), (2, 'Rent')]),
        ),
    ]
