# Generated by Django 3.2.4 on 2021-07-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_postimage_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercial',
            old_name='Area',
            new_name='area',
        ),
        migrations.AlterField(
            model_name='commercial',
            name='floorplan',
            field=models.ImageField(default='none', upload_to='floorplan_images/'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='main_image',
            field=models.ImageField(default='none', upload_to='main_images/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
