# Generated by Django 3.2.4 on 2021-06-30 10:24

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_postresiimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='Area',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='residential',
            name='Area',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='residential',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('key1', 'Near to School'), ('key2', 'Near to Hospital'), ('key3', 'Close to Airport'), ('key4', 'Close to Market'), ('key5', 'Swimming Pool'), ('key6', 'Gym/Fitness Centers'), ('key7', 'Community Clubhouse'), ('key8', 'Community Garden'), ('key9', 'Guest Parking'), ('key10', 'Security Guards'), ('key11', 'CCTV Camera Security'), ('key12', 'Power Backup'), ('key13', '24/7 Water supply'), ('key14', 'Movie Theater'), ('key15', 'Waste disposal'), ('key16', 'Fire Fighting Systems'), ('key17', 'Senior Citizen Sitout'), ('key18', 'Vastu Compliant'), ('key19', 'Entrance Lobby')], max_length=104),
        ),
    ]
