# Generated by Django 3.2.4 on 2021-06-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210630_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='residential',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
