# Generated by Django 3.2.3 on 2021-07-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_postresiimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postresiimage',
            name='images',
            field=models.ImageField(upload_to='post_images/'),
        ),
    ]
