# Generated by Django 3.2.3 on 2021-07-05 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210630_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercial',
            name='timestamp',
        ),
    ]
