# Generated by Django 3.2.3 on 2021-07-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_commercial_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='slug',
            field=models.SlugField(),
        ),
    ]
