# Generated by Django 3.2.3 on 2021-07-05 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_commercial_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
