# Generated by Django 3.2.3 on 2021-07-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_commercial_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='floorplan',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='main_image',
            field=models.ImageField(default='none', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.FileField(upload_to='images/'),
        ),
    ]
