# Generated by Django 3.2.3 on 2021-07-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210706_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='floorplan',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='main_image',
            field=models.ImageField(default='none', upload_to='images'),
        ),
    ]
