# Generated by Django 3.2.3 on 2021-07-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210706_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='main_image',
            field=models.ImageField(default='none', upload_to='images/'),
        ),
    ]
