# Generated by Django 3.2.3 on 2021-07-06 02:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_commercial_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('key1', 'Near to School'), ('key2', 'Near to Hospital'), ('key3', 'Close to Airport'), ('key4', 'Close to Market')], max_length=19),
        ),
    ]
