# Generated by Django 3.2.4 on 2021-07-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210706_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercial',
            name='user',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.FileField(upload_to='nav_page/images/'),
        ),
        migrations.AlterField(
            model_name='postresiimage',
            name='images',
            field=models.FileField(upload_to='resipage_nav/images/'),
        ),
    ]
