# Generated by Django 3.2.3 on 2021-07-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210706_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
