# Generated by Django 3.2.4 on 2021-07-07 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_postimage_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercial',
            name='slug',
        ),
    ]
